spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatrooms
      auto-index-creation: true
  rsocket:
    server:
      #transport: websocket
      port: 7001
  redis:
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

